/**
 * Day 1 audit taxonomy. Use these values for `eventType` / `objectType` consistency.
 * `objectType` describes the primary entity the event refers to (e.g. User, Workspace).
 */
export const AUDIT_EVENT_TYPES = {
  USER_SIGNED_UP: "USER_SIGNED_UP",
  USER_SIGNED_IN: "USER_SIGNED_IN",
  USER_SIGNED_OUT: "USER_SIGNED_OUT",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_COMPLETED: "PASSWORD_RESET_COMPLETED",
  
  WORKSPACE_CREATED: "WORKSPACE_CREATED",
  WORKSPACE_PROFILE_UPDATED: "WORKSPACE_PROFILE_UPDATED",
  WORKSPACE_ACCESS_DENIED: "WORKSPACE_ACCESS_DENIED",
  
  SIGNAL_CONFIRMED: "SIGNAL_CONFIRMED",
  SIGNAL_REJECTED: "SIGNAL_REJECTED",
  SIGNAL_EDITED: "SIGNAL_EDITED",
  
  USER_INVITED: "USER_INVITED",
  INVITE_RESENT: "INVITE_RESENT",
  INVITE_REVOKED: "INVITE_REVOKED",
  INVITE_ACCEPTED: "INVITE_ACCEPTED",
  ACCOUNT_CREATED_FROM_INVITE: "ACCOUNT_CREATED_FROM_INVITE",
  
  ROLE_CHANGED: "ROLE_CHANGED",
  MEMBERSHIP_SUSPENDED: "MEMBERSHIP_SUSPENDED",
  MEMBERSHIP_REACTIVATED: "MEMBERSHIP_REACTIVATED",
  MEMBERSHIP_REMOVED: "MEMBERSHIP_REMOVED",
  
  ANSWER_OWNER_CHANGED: "ANSWER_OWNER_CHANGED",
  TOPIC_OWNER_CHANGED: "TOPIC_OWNER_CHANGED",
  APPROVER_CHANGED: "APPROVER_CHANGED",
  GOVERNANCE_ASSIGNMENT_UPDATED: "GOVERNANCE_ASSIGNMENT_UPDATED",

  SOURCE_DOCUMENT_RECORD_CREATED: "SOURCE_DOCUMENT_RECORD_CREATED",
  SOURCE_DOCUMENT_UPLOAD_STARTED: "SOURCE_DOCUMENT_UPLOAD_STARTED",
  SOURCE_DOCUMENT_UPLOAD_SUCCEEDED: "SOURCE_DOCUMENT_UPLOAD_SUCCEEDED",
  SOURCE_DOCUMENT_UPLOAD_FAILED: "SOURCE_DOCUMENT_UPLOAD_FAILED",
  SOURCE_DOCUMENT_DOWNLOADED: "SOURCE_DOCUMENT_DOWNLOADED",
  SOURCE_DOCUMENT_PARSE_JOB_CREATED: "SOURCE_DOCUMENT_PARSE_JOB_CREATED",
  SOURCE_DOCUMENT_PARSE_JOB_STARTED: "SOURCE_DOCUMENT_PARSE_JOB_STARTED",
  SOURCE_DOCUMENT_PARSE_JOB_COMPLETED: "SOURCE_DOCUMENT_PARSE_JOB_COMPLETED",
  SOURCE_DOCUMENT_PARSE_JOB_FAILED: "SOURCE_DOCUMENT_PARSE_JOB_FAILED",

  ANSWER_LIBRARY_ITEM_CREATED: "ANSWER_LIBRARY_ITEM_CREATED",
  ANSWER_LIBRARY_ITEM_UPDATED: "ANSWER_LIBRARY_ITEM_UPDATED",
  ANSWER_LIBRARY_ITEM_ARCHIVED: "ANSWER_LIBRARY_ITEM_ARCHIVED",

  ANSWER_SUBMITTED_FOR_REVIEW: "ANSWER_SUBMITTED_FOR_REVIEW",
  ANSWER_APPROVED_INTERNAL: "ANSWER_APPROVED_INTERNAL",
  ANSWER_APPROVED_FOR_EXPORT: "ANSWER_APPROVED_FOR_EXPORT",
  ANSWER_EXPORT_SAFE_CONFIRMED: "ANSWER_EXPORT_SAFE_CONFIRMED",
  ANSWER_EXPORT_SAFE_REVOKED: "ANSWER_EXPORT_SAFE_REVOKED",
  ANSWER_REVISION_REQUESTED: "ANSWER_REVISION_REQUESTED",
  ANSWER_WORKFLOW_REJECTED: "ANSWER_WORKFLOW_REJECTED",
  ANSWER_REVIEW_CADENCE_LAPSED: "ANSWER_REVIEW_CADENCE_LAPSED",
  /** New version row persisted for an answer (complements AnswerLibraryItemVersion). */
  ANSWER_LIBRARY_VERSION_RECORDED: "ANSWER_LIBRARY_VERSION_RECORDED",
  /** reviewCadenceDays and/or computed nextReviewDueAt changed on the answer. */
  ANSWER_REVIEW_SCHEDULE_CHANGED: "ANSWER_REVIEW_SCHEDULE_CHANGED",
  ANSWER_EVIDENCE_CHANGE_FLAGGED: "ANSWER_EVIDENCE_CHANGE_FLAGGED",
  
  KNOWLEDGE_TOPIC_CREATED: "KNOWLEDGE_TOPIC_CREATED",
  KNOWLEDGE_TOPIC_UPDATED: "KNOWLEDGE_TOPIC_UPDATED",
  
  QUESTIONNAIRE_JOB_RESCAN: "QUESTIONNAIRE_JOB_RESCAN",
  EXPORT_DOWNLOADED: "EXPORT_DOWNLOADED",

  QUESTIONNAIRE_ITEM_OVERRIDE: "QUESTIONNAIRE_ITEM_OVERRIDE",
  /** Reviewer explicitly chose where the row's `finalAnswer` came from (imported / suggested / edited / canonical_aligned). */
  QUESTIONNAIRE_ITEM_FINAL_ANSWER_SELECTED: "QUESTIONNAIRE_ITEM_FINAL_ANSWER_SELECTED",
  /** One-time summary emitted by the imported-answer backfill script. */
  QUESTIONNAIRE_IMPORTED_ANSWER_BACKFILL: "QUESTIONNAIRE_IMPORTED_ANSWER_BACKFILL",
  /** Canonical-vs-row contradiction detected (review load persistence). */
  QUESTIONNAIRE_ITEM_CONTRADICTION_DETECTED: "QUESTIONNAIRE_ITEM_CONTRADICTION_DETECTED",
  /**
   * User acknowledged the row (KEEP_ROW) or edited to align (EDIT_ROW_ALIGN).
   * Legacy rows may use this type with metadata.action for older dismiss/canonical flows.
   */
  QUESTIONNAIRE_ITEM_CONTRADICTION_RESOLVED: "QUESTIONNAIRE_ITEM_CONTRADICTION_RESOLVED",
  /** User dismissed the hit as a false positive (FALSE_POSITIVE). */
  QUESTIONNAIRE_ITEM_CONTRADICTION_DISMISSED: "QUESTIONNAIRE_ITEM_CONTRADICTION_DISMISSED",
  /** User requested a library/canonical update (REQUEST_CANONICAL_UPDATE). */
  QUESTIONNAIRE_ITEM_CANONICAL_UPDATE_REQUESTED: "QUESTIONNAIRE_ITEM_CANONICAL_UPDATE_REQUESTED",
  ANSWER_LIBRARY_OVERRIDE: "ANSWER_LIBRARY_OVERRIDE",

  QUESTIONNAIRE_ASSIGNEE_CHANGED: "QUESTIONNAIRE_ASSIGNEE_CHANGED",

  WORKSPACE_ARCHIVED: "WORKSPACE_ARCHIVED",
  WORKSPACE_INVITES_REVOKED_BULK: "WORKSPACE_INVITES_REVOKED_BULK",
  WORKSPACE_EXPORT_DEFAULTS_RESET: "WORKSPACE_EXPORT_DEFAULTS_RESET",
  
  ADMIN_ACCESS_GRANTED: "ADMIN_ACCESS_GRANTED",
  ADMIN_ACCESS_DENIED: "ADMIN_ACCESS_DENIED",
} as const;

export const AUDIT_OBJECT_TYPES = {
  USER: "User",
  WORKSPACE: "Workspace",
  WORKSPACE_MEMBERSHIP: "WorkspaceMembership",
  SOURCE_DOCUMENT: "SourceDocument",
  SOURCE_DOCUMENT_PARSE_JOB: "SourceDocumentParseJob",
  AUTH_CONTEXT: "AuthContext",
  ANSWER_LIBRARY_ITEM: "AnswerLibraryItem",
  QUESTIONNAIRE_JOB: "QuestionnaireJob",
  EXPORT_JOB: "ExportJob",
  KNOWLEDGE_TOPIC: "KnowledgeTopic",
  SUB_CONTROL_GOVERNANCE: "SubControlGovernance",
  QUESTIONNAIRE_ITEM: "QuestionnaireItem",
} as const;


export type AuditEventType = (typeof AUDIT_EVENT_TYPES)[keyof typeof AUDIT_EVENT_TYPES];
export type AuditObjectType = (typeof AUDIT_OBJECT_TYPES)[keyof typeof AUDIT_OBJECT_TYPES];
