const fs = require('fs');
const path = require('path');

const filePath = path.join(process.cwd(), 'src/app/onboarding/onboarding-workspace-form.tsx');
let content = fs.readFileSync(filePath, 'utf8');

// Normalize line endings
content = content.replace(/\r\n/g, '\n');
const lines = content.split('\n');

const startIdx = lines.findIndex(l => l.includes('if (step === "RECOMMENDATIONS") {'));
const endIdx = lines.findIndex(l => l.includes('if (step === "ANALYZING") {'));

if (startIdx !== -1 && endIdx !== -1) {
    const newBlock = [
        '  if (step === "RECOMMENDATIONS") {',
        '    return (',
        '      <div className="flex flex-col gap-6">',
        '        <div className="flex items-center gap-2 text-accent-primary">',
        '          <SparklesIcon className="h-5 w-5" />',
        '          <h2 className="text-lg font-semibold">Recommended for you</h2>',
        '        </div>',
        '        <div className="space-y-1">',
        '          <p className="text-sm text-text-primary font-medium">Topic recommendations are ready.</p>',
        '          <p className="text-xs text-text-muted">',
        '            The core <span className="text-text-primary font-semibold">MVP Backbone</span> is always active. ',
        '            Review and approve these extra topics to broaden your Trust Center.',
        '          </p>',
        '        </div>',
        '',
        '        <div className="space-y-6">',
        '          {recommendedPacks.map(pack => (',
        '            <div key={pack.id} className="rounded-xl border border-surface-border bg-surface-base p-4">',
        '              <div className="mb-3">',
        '                <h3 className="text-sm font-semibold text-text-primary">{pack.name}</h3>',
        '                <p className="text-xs text-text-muted">{pack.description}</p>',
        '              </div>',
        '              <div className="grid grid-cols-1 gap-2">',
        '                {pack.topics.map(topic => (',
        '                  <label ',
        '                    key={topic.key}',
        '                    className={`flex cursor-pointer items-start gap-3 rounded-lg border p-3 transition-all ${selectedTopicKeys.has(topic.key) ? "border-accent-primary/50 bg-accent-primary/5" : "border-transparent bg-surface-base-hover hover:border-surface-border"}`}',
        '                  >',
        '                    <input ',
        '                      type="checkbox" ',
        '                      className="hidden"',
        '                      checked={selectedTopicKeys.has(topic.key)}',
        '                      onChange={() => toggleTopic(topic.key)}',
        '                    />',
        '                    <div className={`mt-0.5 flex h-4 w-4 shrink-0 items-center justify-center rounded border ${selectedTopicKeys.has(topic.key) ? "border-accent-primary bg-accent-primary text-white" : "border-surface-border"}`}',
        '                    >',
        '                      {selectedTopicKeys.has(topic.key) && <CheckIcon className="h-3 w-3" />}',
        '                    </div>',
        '                    <div>',
        '                      <div className="text-xs font-medium text-text-primary">{topic.name}</div>',
        '                      <div className="text-[10px] text-text-muted leading-relaxed">{topic.description}</div>',
        '                    </div>',
        '                  </label>',
        '                ))}',
        '              </div>',
        '            </div>',
        '          ))}',
        '',
        '          {isTailoring && (',
        '            <div className="py-24 flex flex-col items-center justify-center gap-4 animate-in fade-in zoom-in duration-500">',
        '               <div className="relative">',
        '                  <div className="absolute inset-0 bg-accent-primary/20 rounded-full blur-xl animate-pulse" />',
        '                  <SparklesIcon className="h-10 w-10 text-accent-primary relative animate-bounce" />',
        '               </div>',
        '               <div className="text-center space-y-1">',
        '                  <p className="text-sm font-bold text-text-primary">Tailoring Evidence Guidance</p>',
        '                  <p className="text-xs text-text-muted">Aligning recommendations with your {industry} profile...</p>',
        '               </div>',
        '            </div>',
        '          )}',
        '',
        '          {!isTailoring && recommendedDocs.length > 0 && (',
        '            <div className="pt-2 animate-in fade-in slide-in-from-bottom-2 duration-500">',
        '               <div className="flex items-center gap-2 text-text-secondary mb-4">',
        '                 <FileTextIcon className="h-4 w-4" />',
        '                 <h3 className="text-sm font-bold">Recommended Library Starters</h3>',
        '               </div>',
        '               <div className="space-y-4">',
        '                 {recommendedDocs.map(doc => (',
        '                   <RecommendedDocumentCard ',
        '                     key={doc.id} ',
        '                     doc={doc} ',
        '                     isAdopted={adoptedIds.has(doc.id)}',
        '                     isGenerating={generatingTemplateId === doc.id}',
        '                     onViewSample={() => setPreviewDoc(doc)}',
        '                     onAdopt={() => setAdoptedIds(new Set([...adoptedIds, doc.id]))}',
        '                     onDownloadDocx={() => onDownloadDocx(doc.id)}',
        '                   />',
        '                 ))}',
        '               </div>',
        '               <p className="mt-6 text-[10px] text-text-muted italic bg-surface-base-hover p-4 rounded-xl border border-surface-border border-dashed leading-relaxed">',
        '                 <span className="font-bold text-text-secondary block mb-1">Pro Tip: Accelerated Seeding</span>',
        '                 These AI-generated sections and descriptions are tailored to your business model. Adopting our templates now will automatically seed your Trust Hub with compliance-ready content.',
        '               </p>',
        '            </div>',
        '          )}',
        '',
        '          {previewDoc && (',
        '            <DocumentSampleModal ',
        '              doc={previewDoc} ',
        '              onClose={() => setPreviewDoc(null)} ',
        '              onDownload={() => onDownloadDocx(previewDoc.id)}',
        '            />',
        '          )}',
        '',
        '          <div className="pt-4 border-t border-surface-border">',
        '              <div className="flex items-center gap-2 text-text-muted mb-4 opacity-70">',
        '                  <UserIcon className="h-4 w-4" />',
        '                  <span className="text-[10px] font-bold uppercase tracking-widest">Optional Next Step</span>',
        '              </div>',
        '              <label className="flex items-center gap-3 p-4 rounded-xl border border-surface-border bg-surface-base hover:bg-surface-base-hover cursor-pointer transition-colors group">',
        '                 <input type="checkbox" className="h-4 w-4 rounded border-surface-border text-accent-primary focus:ring-accent-primary focus:ring-offset-surface-panel bg-surface-base" />',
        '                 <div>',
        '                    <div className="text-xs font-bold text-text-primary group-hover:text-accent-primary transition-colors">Invite your Security & Legal team</div>',
        '                    <div className="text-[10px] text-text-muted">Collaborate on questionnaire reviews and document approvals.</div>',
        '                 </div>',
        '              </label>',
        '          </div>',
        '        </div>',
        '',
        '        <div className="flex gap-3">',
        '          <button',
        '            onClick={() => window.location.href = "/app"}',
        '            className="flex-1 rounded-md border border-surface-border px-4 py-2.5 text-sm font-medium text-text-secondary hover:bg-surface-base-hover"',
        '          >',
        '            Skip for now',
        '          </button>',
        '          <button',
        '            onClick={onFinalizeTopics}',
        '            disabled={submitting}',
        '            className="flex-1 rounded-md bg-accent-primary px-4 py-2.5 text-sm font-medium text-white hover:bg-accent-primary-hover disabled:opacity-50"',
        '          >',
        '            {submitting ? "Applying..." : `Add ${selectedTopicKeys.size} Topics`}',
        '          </button>',
        '        </div>',
        '      </div>',
        '    );',
        '  }',
        ''
    ];

    lines.splice(startIdx, endIdx - startIdx, ...newBlock);
    fs.writeFileSync(filePath, lines.join('\n'));
    console.log('Successfully rewrote RECOMMENDATIONS block');
} else {
    console.log('Could not find step markers');
    process.exit(1);
}
